export default {
  index: 'Übersicht',
  glossar: 'Glossar',
  '---': {
    type: 'separator',
    title: '',
  },
  '01-intro': '1 - Einleitung',
  '02-basics': '2 - Grundlagen',
  '03-type-op-func': '3 - Typen, Operatoren, Funktionen',
  '04-if-switch': '4 - Verzweigungen',
  '05-loops': '5 - Schleifen (while)',
  '06-arrays': '6 - Arrays',
  '07-structure': '7 - Objekte und Klassen',
  '08-organize': '8 - Code und Daten organisieren',
  '09-quality': '9 - Codequalität',
  'js-vertiefung': 'JavaScript Vertiefung',
  'js-praxis': 'JavaScript Praxis',
  misc: 'Weiterführendes (KI, Bibliotheken, Tools)',
  git: 'Git und GitHub',
};
