export default {
  '01-openai': 'OpenAI-API',
  '02-libraries': 'Bibliotheken',
  '03-funktionen2': 'Funktionen (Teil 2)',
  '04-arrow_functions': 'Pfeilfunktionen',
  '05-vscode': 'VS Code',
  '06-debugging': 'Debugging',
  '07-fetch': 'Fetch für Web-Daten',
  '08-private': 'Private Eigenschaften',
  '09-extends': 'Vererbung in Klassen',
  '10-static': 'Statische Methoden',
  '11-regexp': 'Reguläre Ausdrücke',
  '12-array-methods': 'Array-Methoden',
  '13-syntax-tipps': 'Syntax-Tipps',
  '14-map_set': 'Map und Set',
  '15-typescript': 'TypeScript',
  '16-tools': 'Weitere Werkzeuge',
  '17-languages': 'Alternative Sprachen',
};
