export default {
  project_structure: 'Projektstruktur',
  libraries: 'Bibliotheken',
  funktionen2: 'Funktionen (Teil 2)',
  arrow_functions: 'Pfeilfunktionen',
  vscode: 'VS Code',
  debugging: 'Debugging',
  fetch: 'Fetch für Web-Daten',
  'try-catch': 'try…catch',
  private: 'Private Eigenschaften',
  extends: 'Vererbung in Klassen',
  static: 'Statische Methoden',
  regexp: 'Reguläre Ausdrücke',
  'array-methods': 'Array-Methoden',
  'syntax-tipps': 'Syntax-Tipps',
  java: 'Ausblick: Java',
  map_set: 'Map und Set',
  typescript: 'TypeScript',
  tools: 'Weitere Werkzeuge',
  languages: 'Alternative Sprachen',
};
