export default {
  openai: 'OpenAI-API',
  libraries: 'Bibliotheken',
  funktionen2: 'Funktionen (Teil 2)',
  arrow_functions: 'Pfeilfunktionen',
  'ai-sdk': 'AI SDK',
  debugging: 'Debugging',
  fetch: 'Fetch für Web-Daten',
  private: 'Private Eigenschaften',
  extends: 'Vererbung in Klassen',
  static: 'Statische Methoden',
  'regexp': 'Reguläre Ausdrücke',
  'array-methods': 'Array-Methoden',
  'syntax-tipps': 'Syntax-Tipps',
  'map_set': 'Map und Set',
  typescript: 'TypeScript',
  tools: 'Weitere Werkzeuge',
  languages: 'Alternative Sprachen',
};
